version: '2.1'

services:
  ambari-server:
    image: ambari-server:1.0
    hostname: ambari-server
    container_name: ambari-server
    ports:
      - "8080:8080"
    networks:
      hdp_net:
        ipv4_address: 10.1.0.10

  namenode:
    image: ambari-agent:1.0
    hostname: namenode
    container_name: namenode
    ports:
      - "50070:50070"
    privileged: false
    depends_on:
      - "ambari-server"
    networks:
      hdp_net:
        ipv4_address: 10.1.0.11
    healthcheck:
        test: ["CMD", "ssh", "-o", "StrictHostKeyChecking=yes", "ambari-server"]
        interval: 3s
        timeout: 2s
        retries: 10

  resourcemanager:
    image: ambari-agent:1.0
    hostname: resourcemanager
    container_name: resourcemanager
    ports:
      - "8088:8088"
      - "19888:19888"
    privileged: false
    depends_on:
      - "node01"
      - "node02"
      - "node03"
    networks:
      hdp_net:
        ipv4_address: 10.1.0.12
    healthcheck:
        test: ["CMD", "ssh", "-o", "StrictHostKeyChecking=yes", "node01"]
        test: ["CMD", "ssh", "-o", "StrictHostKeyChecking=yes", "node02"]
        test: ["CMD", "ssh", "-o", "StrictHostKeyChecking=yes", "node03"]
        interval: 3s
        timeout: 2s
        retries: 10

  master:
    image: ambari-agent:1.0
    hostname: master
    container_name: master
    ports:
      - "3000:3000"
    privileged: false
    depends_on:
      - "resourcemanager"
    networks:
      hdp_net:
        ipv4_address: 10.1.0.13
    healthcheck:
        test: ["CMD", "ssh", "-o", "StrictHostKeyChecking=yes", "resourcemanager"]
        interval: 3s
        timeout: 2s
        retries: 10

  node01:
    image: ambari-agent:1.0
    hostname: node01
    container_name: node01
    privileged: false
    depends_on:
      - "namenode"
    networks:
      hdp_net:
        ipv4_address: 10.1.0.14
    healthcheck:
        test: ["CMD", "ssh", "-o", "StrictHostKeyChecking=yes", "namenode"]
        interval: 3s
        timeout: 2s
        retries: 10

  node02:
    image: ambari-agent:1.0
    hostname: node02
    container_name: node02
    privileged: false
    depends_on:
      - "namenode"
    networks:
      hdp_net:
        ipv4_address: 10.1.0.15
    healthcheck:
        test: ["CMD", "ssh", "-o", "StrictHostKeyChecking=yes", "namenode"]
        interval: 3s
        timeout: 2s
        retries: 10

  node03:
    image: ambari-agent:1.0
    hostname: node03
    container_name: node03
    privileged: false
    depends_on:
      - "namenode"
    networks:
      hdp_net:
        ipv4_address: 10.1.0.16
    healthcheck:
        test: ["CMD", "ssh", "-o", "StrictHostKeyChecking=yes", "namenode"]
        interval: 3s
        timeout: 2s
        retries: 10

networks:
  hdp_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.1.0.0/24
        gateway: 10.1.0.1
